import db from "../models/index.js";
const { sequelize } = db;
import moment from "moment";
import { v4 as uuidv4 } from "uuid";

/**
 * Donation Visit Seeder
 * Creates realistic donation visit scenarios for testing
 * Based on Process 2: Donated Milk Collection workflow
 */

const STAFF_ID = "550e8400-e29b-41d4-a716-446655440003"; // medical_staff from main seeder
const BANK_ID = "550e8400-e29b-41d4-a716-446655440101"; // Central Milk Bank HCMC

/**
 * Generate donation visits for a donor
 * Simulates realistic timeline from registration to multiple donations
 */
async function generateDonationVisitsForDonor(donor) {
  const registrationDate = moment(donor.created_at);
  const visits = [];

  // SCENARIO 1: First donation (3 days after registration)
  // Status: Completed successfully
  const visit1Id = uuidv4();
  visits.push({
    visit_id: visit1Id,
    donor_id: donor.donor_id,
    bank_id: donor.home_bank_id || BANK_ID,
    scheduled_start: registrationDate
      .clone()
      .add(3, "days")
      .hour(9)
      .minute(0)
      .toDate(),
    scheduled_end: registrationDate
      .clone()
      .add(3, "days")
      .hour(10)
      .minute(0)
      .toDate(),
    origin: "system", // Auto-generated by system
    status: "completed",
    health_status: "good",
    health_note: "Donor in good health condition, cleared for donation",
    volume_ml: 150,
    container_count: 3,
    quality_note: "Normal color and consistency",
    points_awarded: 15, // 10 base points + 5 bonus for first donation
    recorded_by: STAFF_ID,
    created_at: registrationDate.clone().add(3, "days").toDate(),
    updated_at: registrationDate.clone().add(3, "days").hour(10).toDate(),
  });

  // SCENARIO 2: Second donation (1 week after first)
  // Status: Completed successfully with higher volume
  const visit2Id = uuidv4();
  visits.push({
    visit_id: visit2Id,
    donor_id: donor.donor_id,
    bank_id: donor.home_bank_id || BANK_ID,
    scheduled_start: registrationDate
      .clone()
      .add(10, "days")
      .hour(14)
      .minute(0)
      .toDate(),
    scheduled_end: registrationDate
      .clone()
      .add(10, "days")
      .hour(15)
      .minute(0)
      .toDate(),
    origin: "system",
    status: "completed",
    health_status: "good",
    health_note: "Excellent health condition",
    volume_ml: 200,
    container_count: 4,
    quality_note: "High quality, good color",
    points_awarded: 20,
    recorded_by: STAFF_ID,
    created_at: registrationDate.clone().add(10, "days").toDate(),
    updated_at: registrationDate.clone().add(10, "days").hour(15).toDate(),
  });

  // SCENARIO 3: Third visit - Cancelled due to bad health
  // Status: Cancelled (donor came but health check failed)
  const visit3Id = uuidv4();
  visits.push({
    visit_id: visit3Id,
    donor_id: donor.donor_id,
    bank_id: donor.home_bank_id || BANK_ID,
    scheduled_start: registrationDate
      .clone()
      .add(17, "days")
      .hour(9)
      .minute(0)
      .toDate(),
    scheduled_end: registrationDate
      .clone()
      .add(17, "days")
      .hour(10)
      .minute(0)
      .toDate(),
    origin: "system",
    status: "cancelled",
    health_status: "bad",
    health_note:
      "Donor has mild fever (37.8°C), not suitable for donation today",
    volume_ml: 0,
    container_count: 0,
    quality_note: "No donation collected due to health condition",
    points_awarded: 0,
    recorded_by: STAFF_ID,
    created_at: registrationDate.clone().add(17, "days").toDate(),
    updated_at: registrationDate
      .clone()
      .add(17, "days")
      .hour(9)
      .minute(30)
      .toDate(),
  });

  // SCENARIO 4: Fourth donation (24 days after registration)
  // Status: Completed
  const visit4Id = uuidv4();
  visits.push({
    visit_id: visit4Id,
    donor_id: donor.donor_id,
    bank_id: donor.home_bank_id || BANK_ID,
    scheduled_start: registrationDate
      .clone()
      .add(24, "days")
      .hour(10)
      .minute(0)
      .toDate(),
    scheduled_end: registrationDate
      .clone()
      .add(24, "days")
      .hour(11)
      .minute(0)
      .toDate(),
    origin: "system",
    status: "completed",
    health_status: "good",
    health_note: "Health restored, cleared for donation",
    volume_ml: 180,
    container_count: 3,
    quality_note: "Good quality",
    points_awarded: 18,
    recorded_by: STAFF_ID,
    created_at: registrationDate.clone().add(24, "days").toDate(),
    updated_at: registrationDate.clone().add(24, "days").hour(11).toDate(),
  });

  // SCENARIO 5: Upcoming scheduled visit (5 days from now)
  // Status: Scheduled (staff has reviewed and confirmed slot)
  const visit5Id = uuidv4();
  visits.push({
    visit_id: visit5Id,
    donor_id: donor.donor_id,
    bank_id: donor.home_bank_id || BANK_ID,
    scheduled_start: moment().add(5, "days").hour(9).minute(0).toDate(),
    scheduled_end: moment().add(5, "days").hour(10).minute(0).toDate(),
    origin: "system",
    status: "scheduled", // Staff has confirmed the appointment
    health_status: null, // Not checked yet
    health_note: null,
    volume_ml: null,
    container_count: null,
    quality_note: null,
    points_awarded: 0,
    recorded_by: null,
    created_at: moment().subtract(2, "days").toDate(),
    updated_at: moment().subtract(1, "days").toDate(),
  });

  // SCENARIO 6: Proposed visit (12 days from now)
  // Status: Proposed (auto-generated, waiting for staff review)
  const visit6Id = uuidv4();
  visits.push({
    visit_id: visit6Id,
    donor_id: donor.donor_id,
    bank_id: donor.home_bank_id || BANK_ID,
    scheduled_start: moment().add(12, "days").hour(14).minute(0).toDate(),
    scheduled_end: moment().add(12, "days").hour(15).minute(0).toDate(),
    origin: "system",
    status: "proposed", // Waiting for staff confirmation
    health_status: null,
    health_note: null,
    volume_ml: null,
    container_count: null,
    quality_note: null,
    points_awarded: 0,
    recorded_by: null,
    created_at: moment().subtract(1, "days").toDate(),
    updated_at: moment().subtract(1, "days").toDate(),
  });

  return visits;
}

/**
 * Generate visit schedules (recurring schedule information)
 * Only for future/upcoming visits that have scheduling rules
 */
async function generateVisitSchedules(visits, donor) {
  const schedules = [];

  // Find future visits (scheduled or proposed)
  const futureVisits = visits.filter((v) =>
    ["scheduled", "proposed"].includes(v.status)
  );

  for (const visit of futureVisits) {
    const visitDate = moment(visit.scheduled_start);
    const weekOfMonth = Math.ceil(visitDate.date() / 7);
    const weekday = visitDate.isoWeekday(); // 1=Mon, 7=Sun

    schedules.push({
      visit_id: visit.visit_id,
      plan_month: visitDate.format("YYYY-MM"),
      plan_type: "monthly_nth_weekday", // e.g., "2nd Wednesday of month"
      day_of_month: null,
      week_of_month: weekOfMonth,
      weekday: weekday,
      window_start: moment(visit.scheduled_start).format("HH:mm:ss"),
      window_end: moment(visit.scheduled_end).format("HH:mm:ss"),
      proposed_on: moment(visit.created_at).toDate(),
      proposed_by: visit.origin === "system" ? null : STAFF_ID,
      reschedule_count: 0,
      rule_snapshot: JSON.stringify({
        weekly_days: donor.weekly_days,
        preferred_start: donor.preferred_start,
        preferred_end: donor.preferred_end,
        max_visits_per_week: donor.max_visits_per_week,
      }),
      updated_at: moment(visit.updated_at).toDate(),
    });
  }

  return schedules;
}

/**
 * Calculate total points from all completed donations
 */
function calculateTotalPoints(visits) {
  return visits
    .filter((v) => v.status === "completed")
    .reduce((sum, v) => sum + v.points_awarded, 0);
}

/**
 * Main seeder function
 */
async function seedDonationVisits() {
  try {
    console.log("🌱 Starting donation visit seeding...");

    // Get all active donors
    const donors = await sequelize.models.Donor.findAll({
      where: {
        donor_status: "active",
      },
      include: [
        {
          model: sequelize.models.User,
          as: "user",
          attributes: ["user_id", "name", "email"],
        },
      ],
    });

    if (donors.length === 0) {
      console.log("⚠️  No active donors found. Run main seeder first.");
      return;
    }

    for (const donor of donors) {
      console.log(`\n📋 Generating visits for donor: ${donor.user?.name}`);

      // Generate donation visits
      const visits = await generateDonationVisitsForDonor(donor);

      // Insert visits
      await sequelize.models.DonationVisit.bulkCreate(visits, {
        ignoreDuplicates: true,
      });
      console.log(`   ✅ Created ${visits.length} donation visits`);

      // Generate visit schedules
      const schedules = await generateVisitSchedules(visits, donor);
      await sequelize.models.VisitSchedule.bulkCreate(schedules, {
        ignoreDuplicates: true,
      });
      console.log(`   ✅ Created ${schedules.length} visit schedules`);

      // Update donor's total points
      const totalPoints = calculateTotalPoints(visits);
      await donor.update({ points_total: totalPoints });
      console.log(`   💎 Updated donor points: ${totalPoints}`);
    }

    console.log("\n🎉 Donation visit seeding completed successfully!");
    console.log("\n📊 Summary:");
    console.log("   - Completed donations (with points) ✅");
    console.log("   - Cancelled visits (health issues) ❌");
    console.log("   - Scheduled upcoming visits 📅");
    console.log("   - Proposed visits (pending staff review) ⏳");
  } catch (error) {
    console.error("❌ Donation visit seeding failed:", error);
    throw error;
  }
}

/**
 * Export seeder data structure for testing
 */
export const donationVisitSeedConfig = {
  scenarios: [
    { days_after_reg: 3, status: "completed", health: "good", volume: 150 },
    { days_after_reg: 10, status: "completed", health: "good", volume: 200 },
    { days_after_reg: 17, status: "cancelled", health: "bad", volume: 0 },
    { days_after_reg: 24, status: "completed", health: "good", volume: 180 },
    { days_from_now: 5, status: "scheduled", health: null, volume: null },
    { days_from_now: 12, status: "proposed", health: null, volume: null },
  ],
};

export { seedDonationVisits };
